### ISSUE TITLE
Settings icon does not work

### ISSUE THREAD

**Issue by jessek** [trovu/trovu#407]
The icon in the upper RHS (three-lines?) to open the settings or reload shortcuts does not work. The page flickers, but the menu does not open. This behavior occurs on the public trovu.net site, as well as local installations.

FWIW, on my local installation, here are the server logs from clicking on the icon:

```
[2024-07-08T16:08:51.860Z]  "GET /index.html" "[[useragent]]"
[2024-07-08T16:08:51.923Z]  "GET /blog/img/rss.svg" "[[useragent]]"
[2024-07-08T16:08:51.927Z]  "GET /blog/img/rss.svg" Error (404): "Not found"
[2024-07-08T16:08:51.987Z]  "GET /index.html" "[[useragent]]"
[2024-07-08T16:08:52.036Z]  "GET /blog/img/rss.svg" "[[useragent]]"
[2024-07-08T16:08:52.037Z]  "GET /blog/img/rss.svg" Error (404): "Not found"
```

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #407</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @jessek</code> (replace <code>20</code> with the amount, and <code>@jessek</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by georgjaehnig** [comment]
Darn, I had seen this yesterday, but it was gone then. Still fine on my localhost. But I can reproduce it on the live instance.

Thanks for reporting, looking into it.

**Comment by georgjaehnig** [comment]
It should be fixed now, please try again.

**Comment by jessek** [comment]
I still have the same issue on both trovu.net and my local installation.

**Comment by georgjaehnig** [comment]
Interesting. For me, it works, both on local and on trovu.net. Maybe try a deep reload (Ctrl-Shift-R).

**Comment by jessek** [comment]
I re-checked trovu.net and you're right, it's working now. 

But I'm still having the problem with my local installation. FWIW, I'm still seeing the same 404 error in the logs. Is there a problem because the /blog directory doesn't exist on the local checkout? Does the code need error handling around that lookup?

**Comment by georgjaehnig** [comment]
> I re-checked trovu.net and you're right, it's working now.

OK. Seems I need to check [cache busting](https://github.com/trovu/trovu/issues/409).

> Is there a problem because the /blog directory doesn't exist on the local checkout? 

Oh right. Yes, the RSS icon on the homepage comes from the blog. You can build it with `npm run build-blog`.

But not sure if you want it on your local instance at all. If not, then probably the links on the homepage will be broken. 

Same is true for the docs link in the menu. The docs can be [build with Python](https://github.com/trovu/trovu/blob/master/.github/workflows/deploy.yml#L29). But I guess there's no point in having all this setup on a local instance.

I guess the easiest solution would be to have a base URL configurable, both for blog and docs. Which you then can set to 

* https://trovu.net/docs/ and
* https://trovu.net/blog

Probably we can use the new `trovu.config.yml` for this.

The only downside would be that the docs on trovu.net might be already for a newer version than is running on your local instance.

Let me know what you think (whether you want to build the docs&blog locally, or link to the official ones).

**Comment by jessek** [comment]
I'd prefer to have the documentation links point to the official sources on trovu.net. There's no point in my hosting that content locally.

**Comment by georgjaehnig** [comment]
@jessek URLs to [blog and docs can be now configured](https://trovu.net/docs/developers/#configuration).

Don't hesitate to reopen if there's still an issue.

**Comment by jessek** [comment]
The good news is that I no longer see 404 errors when I click on the burger icon.

The bad news is that it still doesn't fix the issue. On my local installation, clicking the burger icon causes the page to refresh, but does not open the menu. Verified on both Mac and Linux.

**Comment by jessek** [comment]
Can you please re-open this issue? I don't have the option to do that.

**Comment by georgjaehnig** [comment]
What an odyssey! But we'll get there.

So the broken Settings link was due to a faulty npm update. This should be resolved for sure with a clean install:
```bash
npm run clean
npm ci
npm run build
npm run serve
```

Let me know if that worked. (Redid it on my local machine (Mac) and it does for me.)

**Comment by jessek** [comment]
That worked, thank you!

The burger menu now works on my local installation. 

Thank you for helping me solve this issue! I appreciate your time.
